### ISSUE TITLE
outputReferences not properly resolved when using custom name transform

### ISSUE THREAD

**Issue by spiess-demos** [amzn/style-dictionary#1037]
I apply a custom name transform to my Scss transform group, to align Tailwind with legacy variable names. My config goes like that (for brevity i only show the Scss-related code here, [repo here](https://github.com/demos-europe/demosplan-ui/blob/main/buildTokens.js)):

```Javascript
StyleDictionary.registerTransform({
  name: 'name/scss',
  type: 'name',
  transformer: (token) => {
    // "DEFAULT" is a Tailwind naming convention that should not be part of the Scss name
    if (token.path[1] === 'DEFAULT') {
      token.path.splice(1, 1)
    }
    return token.path.join('-')
  }
})

StyleDictionary.registerTransformGroup({
  name: 'custom/scss',
  transforms: StyleDictionary.transformGroup.scss.concat(['name/scss'])
})

const StyleDictionaryExtended = StyleDictionary.extend({
  source: [tokensPath],
  platforms: {
    scss: {
      transformGroup: 'custom/scss',
      buildPath: 'tokens/dist/scss/',
      files: files.map((filePath) => {
        return {
          destination: `_${filePath}.scss`,
          format: 'scss/variables',
          filter: (token) => token.filePath.includes(filePath),
          options: {
            outputReferences: true
          }
        }
      })
    },
  // ...
  }
})
```

I also keep legacy variables around, aliasing them to the new Tailwind variables:

```Json
{
  "rounded": {
    "none": {
      "value": "0"
    },
    "sm": {
      "value": "2px"
    },
    "smallest": {
      "value": "{rounded.sm}"
    },
    "DEFAULT": {
      "value": "3px"
    },
    "small": {
      "value": "{rounded.DEFAULT}"
    },
    "md": {
      "value": "4px"
    },
    "medium": {
      "value": "{rounded.md}"
    },
    "lg": {
      "value": "5px"
    },
    "large": {
      "value": "{rounded.lg}"
    },
    "full": {
      "value": "9999px"
    }
  }
}
```

Before v3.9.0, this resulted in the desired output:

```Scss
$dp-rounded-full: 9999px;
$dp-rounded-lg: 5px !default;
$dp-rounded-md: 4px !default;
$dp-rounded: 3px !default;
$dp-rounded-sm: 2px !default;
$dp-rounded-none: 0;
$dp-rounded-large: $dp-rounded-lg;
$dp-rounded-medium: $dp-rounded-md;
$dp-rounded-small: $dp-rounded;
$dp-rounded-smallest: $dp-rounded-sm;
```

Since style-dictionary v3.9.0, the alias of the token that has been changed by the name transform (`{rounded.DEFAULT}`) is not being resolved properly anymore:

```Scss
$dp-rounded-full: 9999px;
$dp-rounded-lg: 5px !default;
$dp-rounded-md: 4px !default;
$dp-rounded: 3px !default;
$dp-rounded-sm: 2px !default;
$dp-rounded-none: 0;
$dp-rounded-large: $dp-rounded-lg;
$dp-rounded-medium: $dp-rounded-md;
$dp-rounded-small: {rounded.DEFAULT};
$dp-rounded-smallest: $dp-rounded-sm;
```

Is there any way to work around this on my side, or is it a bug within the latest release of style-dictionary?

**Comment by chris-dura** [comment]
FWIW, I'm seeing the same thing happen with my custom transform (or custom transform group?), when the value is `0`.

I prefer to define tokens in `px`, not `rem`, so I replace the predefined `size/rem` transform in the [predefined `css` transform group](https://amzn.github.io/style-dictionary/#/transform_groups?id=css) with the `size/pxToRem` transform.

```js
/**
 * Transform group for the Web platform.
 * Extends the pre-defined `css` group.
 * - Replaces `size/rem` transform with `size/pxToRem` transform.
 * - Adds custom `size/relativeLineHeight` transform.
 */
module.exports = {
	name: "my-css-group",
	transforms: [
		// from pre-defined `css` group...
		"attribute/cti",
		"name/cti/kebab",
		"time/seconds",
		"content/quote",
		"content/icon",
		"size/pxToRem",
		"size/relativeLineHeight",
		"color/css",
	],
};
```

```scss
// Output style-dictionary@v3.8.0

$dialog-border-width: 0 !default;

// Output style-dictionary@v3.9.0

$dialog-border-width: {border.width.none.value} !default;
```

**Comment by chris-dura** [comment]
Not a defect, but related to the changes made to `outputReferences` in the repo, and maybe worth adding a unit test or failing the builds with an error... 

Related issue...

I (mistakenly) defined a reference with extra space after and before the braces and it compiled fine; however in `v3.9.0` the output has changed. 

```json
	"link-icon-fill": {
		value: "{ color.primary.value }",
	}
```

```scss
// output: v3.8.0

$alert-link-icon-fill: $color-primary !default;

// output: v3.9.0

$alert-link-icon-fill: { color.primary.value } !default;
```

If it is _required_ to have no spaces after/before the braces in a reference, then the build should fail and throw an error.
