### ISSUE TITLE
Wrap tokens for CSS output containing math expressions in calc()

### ISSUE THREAD

**Issue by jorenbroekema** [amzn/style-dictionary#1055]
## Feature Request

For the CSS property formatter.

```css
:root {
  --my-math: 15px + 20px;
}
```

This is invalid CSS, but would be valid if wrapped inside CSS calc() statement. This can be done for any expression using `* / + -` characters.
Important to note is that whatever we do to regex match such tokens is that there must be spaces around the `+` and `-` math operators, see https://developer.mozilla.org/en-US/docs/Web/CSS/calc#notes

Output will then be:
```css
:root {
  --my-math: calc(15px + 20px);
}
```
