### ISSUE TITLE
Transform tokens into data set referecing other root variables

### ISSUE THREAD

**Issue by lwnoble** [amzn/style-dictionary#1142]
I need to transform tokes into data sets referencing other root variables.

I want to transform these tokens: 
```json
{
 "backgrounds": {
  "pink": {
    "background-color": {
      "value": "{mode-colors.magenta-10.background-color}",
      "type": "color"
    },
    "alt-background-color": {
      "value": "{mode-colors.magenta-10.alt-background-color}",
      "type": "color"
    },
    "background-on-color": {
      "value": "{mode-colors.magenta-10.background-on-color}",
      "type": "color"
    },
    "background-on-on-color": {
      "value": "{mode-colors.magenta-10.background-on-on-color}",
      "type": "color"
    },
    "background-on-color-quiet": {
      "value": "{mode-colors.magenta-10.background-on-quiet}",
      "type": "color"
    },
    "background-button": {
      "value": "{mode-colors.magenta-10.background-button}",
      "type": "color"
    },
    "background-button-half": {
      "value": "{mode-colors.magenta-10.background-button-half}",
      "type": "color"
    },
    "background-on-button": {
      "value": "{mode-colors.magenta-10.background-on-button}",
      "type": "color"
    },
    "background-hotlink": {
      "value": "{mode-colors.magenta-10.background-hotlink}",
      "type": "other"
    }
  }
}  
```

Into this css:

```css
[data-background="pink"] {
  --background: var(--mode-colors.magenta-10.background-color);
  --background-alt:  var(--mode-colors.magenta-10.alt-background-color);
  --on-background: var(--mode-colors.magenta-10.background-on-color);
  --on-background-quiet: var(--mode-colors.magenta-10.background-on-quiet);;
  --hotlink: var(--mode-colors.magenta-10.background-hotlink);;
  --border: var(--mode-colors.magenta-10.background-border)
  --button: var(--mode-colors.magenta-10.background-button);
  --on-button: var(--mode-colors.magenta-10.background-on-button);
  --button-half: var(--mode-colors.magenta-10.background-button-half);
  }
```

I know I need to apply, format, and filter, but I don't know where to get started.
