### ISSUE TITLE
Multiple conditional / mode values for a single design token

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#1171]
Hey, I am running into an issue with different scenarios where I need multiple values for on token.

In all cases the value I want is tied to a kind of mode and will be returned within one file, but within selectors or media queries.

### Example 1: dark & light mode
```css
:root,
[data-color-mode="light"] {
  --column-bgColor-overlay: #ec51544d;
}

[data-color-mode="dark"] {
  --column-bgColor-overlay: #ec51544d;
}

```

### Example 2: responsive tokens
```css
:root {
  --spacing-margin: var(--base-size-16);
}

@media (min-width: 768px) {
  :root {
    --spacing-margin: var(--base-size-40);
  }
}

@media (min-width: 1280px) {
  :root {
    --spacing-margin: var(--base-size-24);
  }
}
```

## Problem
Previously I have used multiple files, e.g. `colors.light.json` and `colors.dark.json`. However now, I have component tokens in here as well. Those tokens are defined within the component folders as individual files. E.g. `components/table/table.json`.

Defining files for both modes and media queries for each component does not make for a good workflow. This is why I'd like to define them in one file. However, since the tokens must have the same name, the only approach I have found is the [single token method](https://dbanks.design/blog/dark-mode-with-style-dictionary/#Single-token-method) described by @dbanksdesign. Since it has the huge downside of not running transformers on anything but the `value` property, it feels like a bad solution.

I am wondering if there is any other way of getting this to work.

I was thinking of something like:

```json5
{
  token: {
    value: [
      {
         value: "{base.size.16}" // default
      },
      {
         value: "{base.size.40}"
         $extensions: {
           "myOrg.mediaQuery": "@media (min-width: 768px)"
         }
      },
      {
         value: "{base.size.24}"
         $extensions: {
           "myOrg.mediaQuery": "@media (min-width: 1280px)"
         }
      },
    ]
  }
}
```

However, this needs to run through the transformers, which does not work. If I would get those as transformed values in my formatter, it would be all great.
