### ISSUE TITLE
Combining base and palette

### ISSUE THREAD

**Issue by perkrlsn** [amzn/style-dictionary#1217]
Hello!

This might already be possible but I can't seem to get it to work. What it'd like to do is something like this.

```json
{
  "color": {
    "black": {
      "value": "#000000",
      "100": { "value": "#1A1A1A" }
    }
  }
}
```

Which in turn I'd like to end up as (css variable example).
```css
:root {
  --prefix-color-black: #000000;
  --prefix-color-black-100: #1A1A1A;
}
```

But what ends up happening is `sd` stripping out all my palette colors and only keeping the root black one e.g.
```css
:root {
  --prefix-color-black: #000000;
}
```

 What am I missing?

Thank you!
