### ISSUE TITLE
scss/map-deep formatting not applied to map values

### ISSUE THREAD

**Issue by Stun3R** [amzn/style-dictionary#1286]
Hey 👋🏼 

I just encountered an issue related to formatting options.

It looks like the formatting options only format the SCSS variables' references, not the ones passed to the SCSS map.

**Config:**
```js
{
  sources: ["properties/**/*.json",
  platforms: {
    css: {
      transformGroup: ['attribute/cti', 'name/kebab', 'color/css', 'opacity/css', 'fontFamily/css'],
      buildPath: './dist',
      files: [
        {
          destination: 'style.css',
          format: 'css/variables',
          options: {
            showFileHeader: false,
            selector: '.common',
            formatting: {
              prefix: `--common-`,
            },
          },
        },
      ],
      expand: true,
    },
    scss: {
      transformGroup: ['attribute/cti', 'name/kebab', 'color/css', 'opacity/css', 'fontFamily/css'],
      buildPath: './dist',
      files: [
        {
          destination: 'tokens.scss',
          format: 'scss/map-deep',
          options: {
            showFileHeader: false,
            formatting: {
              prefix: `$common-`,
            },
          },
        },
      ],
    expand: true,
    },
  }
}
```

**CSS result:**
```css
.common {
  --common-duration-veryfast: 100ms;
  --common-duration-fast: 250ms;
  --common-duration-medium: 500ms;
  --common-duration-slow: 1000ms;
  --common-duration-veryslow: 2000ms;
  --common-opacity-highlight: 0.2;
  --common-opacity-disabled: 0.5;
  --common-opacity-loading: 0.8;
  --common-opacity-image-hover: 0.8;
  --common-breakpoint-mobile-small: 390px;
  --common-breakpoint-mobile: 600px;
  --common-breakpoint-tablet-small: 720px;
  --common-breakpoint-tablet: 960px;
  --common-breakpoint-desktop-small: 1280px;
  --common-breakpoint-desktop: 1920px;
  --common-effect-material-blur: 50px;
  --common-z-index-app-bar: 1100;
  --common-z-index-drawer: 1200;
  --common-z-index-modal: 1300;
  --common-z-index-snackbar: 1400;
  --common-z-index-tooltip: 1500;
}
```

**SCSS result**
```scss
$common-z-index-tooltip: 1500 !default;
$common-z-index-snackbar: 1400 !default;
$common-z-index-modal: 1300 !default;
$common-z-index-drawer: 1200 !default;
$common-z-index-app-bar: 1100 !default;
$common-effect-material-blur: 50px !default;
$common-breakpoint-desktop: 1920px !default;
$common-breakpoint-desktop-small: 1280px !default;
$common-breakpoint-tablet: 960px !default;
$common-breakpoint-tablet-small: 720px !default;
$common-breakpoint-mobile: 600px !default;
$common-breakpoint-mobile-small: 390px !default;
$common-opacity-image-hover: 0.8 !default;
$common-opacity-loading: 0.8 !default;
$common-opacity-disabled: 0.5 !default;
$common-opacity-highlight: 0.2 !default;
$common-duration-veryslow: 2000ms !default;
$common-duration-slow: 1000ms !default;
$common-duration-medium: 500ms !default;
$common-duration-fast: 250ms !default;
$common-duration-veryfast: 100ms !default;

$tokens: (
  'duration': (
    'veryfast': $duration-veryfast,
    'fast': $duration-fast,
    'medium': $duration-medium,
    'slow': $duration-slow,
    'veryslow': $duration-veryslow
  ),
  'opacity': (
    'highlight': $opacity-highlight,
    'disabled': $opacity-disabled,
    'loading': $opacity-loading,
    'image-hover': $opacity-image-hover
  ),
  'breakpoint': (
    'mobile-small': $breakpoint-mobile-small,
    'mobile': $breakpoint-mobile,
    'tablet-small': $breakpoint-tablet-small,
    'tablet': $breakpoint-tablet,
    'desktop-small': $breakpoint-desktop-small,
    'desktop': $breakpoint-desktop
  ),
  'effect': (
    'material': (
      'blur': $effect-material-blur
    )
  ),
  'z-index': (
    'app-bar': $z-index-app-bar,
    'drawer': $z-index-drawer,
    'modal': $z-index-modal,
    'snackbar': $z-index-snackbar,
    'tooltip': $z-index-tooltip
  )
);
```

After looking at the [scss/map-deep format](https://github.com/amzn/style-dictionary/blob/main/lib/common/formats.js#L162), I noticed that the whole dictionary is passed to the registered template but not the formatting options. The SCSS map is built via a [processJsonNode](https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/scss/map-deep.template.js#L14), which doesn't take into account those options.
