### ISSUE TITLE
Support Global Token Reference After CSS Variable Conversion

### ISSUE THREAD

**Issue by sakit0** [amzn/style-dictionary#1361]
**Summary:**  
I would like to propose an enhancement where tokens can reference global tokens after CSS variable conversion. The goal is to ensure that when a token references a global token (e.g., a color variable like `white`), the reference to that global token is preserved during the conversion process.

---

**Current behavior:**  
Global tokens are defined separately from light theme tokens.  

For example

GlobalToken.json

```json
{
  "white": {
    "$type": "color",
    "$value": "#ffffff"
  }
}

```
Light.json
```json

{
  "primary": {
    "$type": "color",
    "$value": "{white}"
  }
}

```

The current output in CSS looks like this:

```css
:root {
  --white: #ffffff;
  --primary: #000000;
}
```

**Expected behavior:**
The `primary` token should reference the global `white` token, so the ideal CSS output should look like this:

```css
:root {
  --white: #ffffff;
  --primary: var(--white);
}
```

This enhancement would improve token management by ensuring references between tokens are maintained across themes and token files, making the system more modular and scalable.

Or is there a way to achieve this?
