### ISSUE TITLE
【Help】Why can't we generate multiple theme files with the same CSS variables

### ISSUE THREAD

**Issue by yanquanfahei** [amzn/style-dictionary#1373]
How can I change the configuration in the [example](https://stackblitz.com/edit/stackblitz-starters-oheymv)  to generate the following result：
```css
/* global.css */
:root {
  --size-regular: 14rem;
  --size-small: 12rem;
  --colors-black: #000000;
  --colors-white: #ffffff;
}

/* light.css */
html[data-theme="light"] {
  --text-primary: var(--colors-black);
}

/* dark.css */
html[data-theme="dark"]{
  --text-primary: var(--colors-white);
}
```
