### ISSUE TITLE
CSS variables with light-dark()?

### ISSUE THREAD

**Issue by brian-patrick-3** [amzn/style-dictionary#1377]
Having a light and a dark theme, is it possible to generate variables using the CSS `light-dark()` syntax?

Ex desired output:
```css
:root {
  /* palette tokens */
  --kd-color-black: #000;
  --kd-color-white: #fff;
    
  /* named tokens */
  --kd-color-text: light-dark(var(--kd-color-black), var(--kd-color-white));
  --kd-color-background: light-dark(var(--kd-color-white), var(--kd-color-black));
}
```
