### ISSUE TITLE
Is it possible to group tokens into reusable text styles?

### ISSUE THREAD

**Issue by alfred1000351** [amzn/style-dictionary#1440]
Hi 

I've been trying to figure this out for a while now with no luck. Below, I have my JSON for my typography token, and when I run my config, the tokens are created as separate lines. However, since it's typography, I'm trying to make it easier to use in the code. Ideally, it should generate a reusable text style that includes all the necessary properties.

I've tried several different ways to create a custom formatter, but nothing has worked. I'm using Style Dictionary v4.

End Goal
```scss
 .typography-desktop-body-strong-xl-strong {
    font-family: var(--typography-desktop-body-strong-xl-strong-font-family), sans-serif;
    font-weight: var(--typography-desktop-body-strong-xl-strong-font-weight);
    line-height: var(--typography-desktop-body-strong-xl-strong-line-height);
    font-size: var(--typography-desktop-body-strong-xl-strong-font-size);
    letter-spacing: var(--typography-desktop-body-strong-xl-strong-letter-spacing);
    text-transform: var(--typography-desktop-body-strong-xl-strong-text-case);
    text-decoration: var(--typography-desktop-body-strong-xl-strong-text-decoration);
  }`
```

variables.css file
```scss
  --typography-desktop-body-strong-xl-strong-font-family: Stolzl;
  --typography-desktop-body-strong-xl-strong-font-weight: Bold;
  --typography-desktop-body-strong-xl-strong-line-height: 20px;
  --typography-desktop-body-strong-xl-strong-font-size: 20px;
  --typography-desktop-body-strong-xl-strong-letter-spacing: 0%;
  --typography-desktop-body-strong-xl-strong-paragraph-spacing: 20px;
  --typography-desktop-body-strong-xl-strong-paragraph-indent: 0px;
  --typography-desktop-body-strong-xl-strong-text-case: none;
  --typography-desktop-body-strong-xl-strong-text-decoration: none;
```

My token.json file

```json
{
    "Typography": {
      "Desktop": {
        "body": {
          "regular": {
            "xl": {
              "fontFamily": {
                "value": "{fontFamilies.stolzl}",
                "type": "fontFamilies"
              },
              "fontWeight": {
                "value": "{fontWeights.stolzl-0}",
                "type": "fontWeights"
              },
              "lineHeight": {
                "value": "{lineHeights.0}",
                "type": "lineHeights"
              },
              "fontSize": {
                "value": "{fontSize.2}",
                "type": "fontSizes"
              },
              "letterSpacing": {
                "value": "{letterSpacing.0}",
                "type": "letterSpacing"
              },
              "paragraphSpacing": {
                "value": "{paragraphSpacing.1}",
                "type": "paragraphSpacing"
              },
              "paragraphIndent": {
                "value": "{paragraphIndent.0}",
                "type": "paragraphIndent"
              },
              "textCase": {
                "value": "{textCase.none}",
                "type": "textCase"
              },
              "textDecoration": {
                "value": "{textDecoration.none}",
                "type": "textDecoration"
              }
            }
          }
        }
      }
    }
  }
```
