### ISSUE TITLE
[Proposal] support selector option as string array in css/variables formatter

### ISSUE THREAD

**Issue by YumiChen** [amzn/style-dictionary#1485]
## Use case
We're using style-dictionary to generate multiple CSS stylesheets containing CSS variables. We'd like the variable values to be overridden at different device breakpoints and in light/ dark mode, which would require the variables to be nested in a media query. Currently this is not achievable with `css/variables` formatter `selector` option:
```css
/* selector as @media (max-width: 768px) */
/* Invalid CSS, a selector should be nested in the media query */
@media (max-width: 768px) {
    --color-primary: white; 
}  

/* selector as @media (max-width: 768px) :root { */
/* Invalid CSS, a closing curly bracking is missing at the end */
@media (max-width: 768px) :root { {
    --color-primary: white; 
}  
```

Expected output
```css
@media (max-width: 768px) {
  :root { 
    --color-primary: white; 
  }
}
```

This may also be useful for other queries like `@supports` and `@container`

## Proposal
Having the selector option support both `string` and `string[]`, so that the selectors could be nested
```js
{
  "platforms": {
    "css": {
      "files": [{
        "format": "css/variables",
        "selector": ["@media (max-width: 768px)", ":root"] // supports array
      }]
    }
  }
}
```

I'll create a PR draft for better reference
