### ISSUE TITLE
Support nesting/chaining in output formats

### ISSUE THREAD

**Issue by nategreen** [amzn/style-dictionary#349]
This is a feature request nested in a question. (See what I did there?)

Is it possible for Style Dictionary's outputs to match the references from the source, for formats that support it? So, instead of:

```css
:root {
  --var-a: #fff;
  --var-b: #fff;
  --var-c: #fff;
}
```

have it be something like:

```css
:root {
  --var-a: #fff;
  --var-b: var(--var-a);
  --var-c: var(--var-a);
}
```

I'm assuming since none of the formats (that I've tried) do it that way, it's not possible at the moment—but maybe I missed something.
