### ISSUE TITLE
support for private tokens

### ISSUE THREAD

**Issue by tlouisse** [amzn/style-dictionary#523]
Hi,

I was wondering whether support for private tokens could be built in (currently I have to apply custom filters to all files in all platforms).

### What are private tokens?

Imagine you have a Design System with dark and light mode, exposing semantic color names to its users, so that you end up with:

✅ **public** output
```css
html {
   --color-primary: #ffff00;
   --color-secondary: #800080;
  /* etc... */
}

html[theme=dark] {
   --color-primary: #008000;
   --color-secondary: #0000ff;
  /* etc... */
}
```

These dark and light modes pick from a color palette that should not be exposed to consumers:

:wrench: **private** color primitives 
```js
{ 
  color: {
    yellow: { value: '#ffff00', isPrivate: true },
    green: { value: '#008000', isPrivate: true },
   ...
  }
}
```

In the examples below we consume this private primitives palette: 

:wrench: **public** light mode
```js
{ 
  color: {
    primary: { value: '{color.yellow}'  },
    secondary: { value: '{color.purple}' },
  }
}
```

:wrench: **public** dark mode
```js
{ 
  color: {
    primary: { value: '{color.green}'  },
    secondary: { value: '{color.blue}' },
  }
}
```

By default, this would be outputted to the consumer:

❌  **private**, so we don't want to expose this...
```css
html {
   --color-yellow: #ffff00;
   --color-green: #008000;
  /* etc... */
}
```
The `isPrivate` flag prevents these from being outputted to the consumer. In this way we are sure the consumer applies `--color-primary` and `--color-secondary` instead, so that the app he builds will work correctly in light- and dark mode.

Would it be possible to support such a concept?
I would be willing to do a merge request for it...
