### ISSUE TITLE
output multi references in one value e.g. `--c-hsl: hsl(var(--c-h), var(--c-s), 11%);`?

### ISSUE THREAD

**Issue by uptonking** [amzn/style-dictionary#565]
- some property value may consist of several parts, such as border, padding.
- how can we combine `outputReferences` and transitive transform to output a value referencing multiple css variables
- my goal is to output a css variable like `--color-btn-hsl: hsl(var(--color-btn-h), var(--color-btn-s), 11%);`

tokens source:  
``` json
{
  "color": {    
    "btn": {
      "h": { "value": 10, "outputAsItIs": true },
      "s": { "value": "12%", "outputAsItIs": true },
      "l": { "value": "12%", "outputAsItIs": true },
      "hsl": {
        "value": {
          "h": "color.btn.h",
          "s": "color.btn.s",
          "l": "color.btn.l"
        }
      }
    }
  }
}

```
- problem is simplified here: 
  - only output css files with css variables, without considering other platform formats
  - with `outputAsItIs` option,  `color/css` transform will skip the h, s, l prop value.

expected output:
``` css
:root {
  --color-btn-h: 10;
  --color-btn-s: 12%;
  --color-btn-l: 12%;
  --color-btn-hsl: hsl(var(--color-btn-h), var(--color-btn-s), 11%);
}
```
