### ISSUE TITLE
Adding a setting for path prefix of font files

### ISSUE THREAD

**Issue by nhoizey** [amzn/style-dictionary#576]
I see in [the template for CSS fonts](https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/css/fonts.css.template) that there is a `../` prefix added to all font file paths coming from tokens.

Depending on where/how the CSS will be used, this `../` might not be relevant.

Would it be possible to make this prefix configurable?

**Comment by dbanksdesign** [comment]
To be honest, that template is not great and I didn't know if anyone actually used it. There are probably a lot of improvements we can do to make it more generic and useful.

**Comment by nhoizey** [comment]
I agree it's not great, not only because of this prefix.

The WOFF2 format is listed last, while it should be first, because it's the best one for the Web performance, and the browser takes the first one it "understands".

We could also keep only WOFF and WOFF2, unless we want to keep supporting IE 11:
https://www.zachleat.com/web/retire-bulletproof-syntax/

Here's the template I made for my current project, but I don't know yet how to provide the `fontPathPrefix` value:

```
<% _.forIn(properties && properties.asset && properties.asset.font, function(font) {
  var fileFormatArr = [];
  if (font.woff2) {
  	fileFormatArr.push("url('" + fontPathPrefix + font.woff2.value + "') format('woff2')");
  }
  if (font.woff) {
  	fileFormatArr.push("url('" + fontPathPrefix + font.woff.value + "') format('woff')");
  }
%>
@font-face {
  font-family: "<%= font.name.value %>";
  src: <%= fileFormatArr.join(',\n\t\t') %>;<% if (font.style) { %>
  font-style: <%= font.style.value %>;<% } if (font.weight) { %>
  font-weight: <%= font.weight.value %>;<% } %>
}
<% }); %>
```

**Comment by 7studio** [comment]
I haven't thought about generating `@font-face` rule with the help of templating before but it's a brilliant idea :astonished: 
That remembers me of a very old but useful project [7studio/bichoco-font-faces](https://github.com/7studio/bichoco-font-faces)
@nhoizey have you already tried a tokens organisation to generate the rules?
This idea makes my day :grinning:

**Comment by nhoizey** [comment]
@7studio sorry I don't understand exactly what you mean. 😅

**Comment by 7studio** [comment]
@nhoizey I talked about the `tokens/assets/fonts.json` file.
I thought about something like that:
```
{
  "asset": {
    "font": {
      "sourcecodepro": {
        "family": { "value": "Source Code Pro" },
        "descriptors": { "value": ["400"] }
      },
      "sourcesanspro": {
        "family": { "value": "Source Sans Pro" },
        "formats": { "value": ["woff", "woff2"] },
        "descriptors": { "value": ["400", "i400", "600", "i600", "700", "i700"] },
        "display": { "value": "swap" }
      }
    }
  }
}
```
It's just a draft and I'm not very convinced of the `descriptors` entry (maybe we should follow the google fonts one) but this schema is much flexible than the existing one to generate rules.

**Comment by nhoizey** [comment]
@7studio ok, I understand, you want to have all the font face properties as tokens. I agree it's necessary.

I also agree `descriptors` doesn't look right. How do you find the actual font name (thin, regular, semi bold, bold, etc.) from these values?

**Comment by 7studio** [comment]
I have an object to do the job in the template:
```
/**
 * Steps to process fonts correctly:
 *
 * 1. Go on https://www.fontsquirrel.com/tools/webfont-generator
 * 2. Upload the `/src/assets/fonts/generator_config.txt` config file
 * 3. Upload your fonts
 * 4. Install them into `/src/assets/fonts/` following these guidelines
 *    https://github.com/7studio/bichoco-font-faces
 *
 *
 * Please, don't edit this file manually. 
 * Check the tokens file there: `style-dictionary/properties/asset/font/`.
 */

<%
var wghtFileDescriptorNames = { '100': 'thin', '200': 'extralight', '300': 'light', '400': 'regular', '500': 'medium', '600': 'semibold', '700': 'bold', '800': 'extrabold', '900': 'black', };
Object.values(properties && properties.asset && properties.asset.font || {}).forEach(font => {
  var formats = font.formats ? font.formats.value : ['woff', 'woff2'];
  var display = font.display ? font.display.value : 'auto';
  
  font.descriptors.value.forEach(desc => {

    var isItal = desc[0] === 'i';
    var wght = isItal ? desc.slice(1, 4) : desc;

    var fileFormatArr = [];
    formats.forEach(frmt => {
      var url = `/assets/fonts/${font.family.value}/${wghtFileDescriptorNames[wght]}${isItal ? '-italic' : ''}.${frmt}`;
      
      fileFormatArr.push(`url("${url}") format("${frmt}")`);
    })
%>
@font-face {
  font-family: "<%= font.family.value %>";
  src: <%= fileFormatArr.join(',\n\t\t   ') %>;
  font-style: <%= isItal ? 'italic' : 'normal' %>;
  font-weight: <%= wght %>;
  font-display: <%= display %>;
}
<% }); %>

<% }); %>
```
For the moment, this template doesn't handle all cases (all formats, unicode-range, etc).

**Comment by nhoizey** [comment]
@7studio this is really nice! 👍

Are these `wghtFileDescriptorNames` values a standard across fonts?

And be careful with the `formats` value `['woff', 'woff2']` as you should have the `woff2` before the `woff` in the `@font-face` declaration.

**Comment by nhoizey** [comment]
Ok, i found this on MDN: [Common weight name mapping](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight#common_weight_name_mapping)

**Comment by nhoizey** [comment]
Here's what I just did (the repository is unfortunately private):

I have tokens for font weights in `tokens/options/number/font.json`:

```json
{
  "number": {
    "font": {
      "weight": {
        "medium": {
          "value": "500",
          "comment": "Medium"
        },
        "semibold": {
          "value": "600",
          "comment": "Semibold"
        },
        "bold": {
          "value": "700",
          "comment": "Bold"
        }
      }
    }
  }
}
```

I have tokens for font faces in `tokens/options/asset/font.json`:

```json
{
  "asset": {
    "font": {
      "sharpsans": {
        "family": {
          "value": "Sharp Sans"
        },
        "formats": { "value": ["woff2", "woff"] },
        "display": {
          "value": "swap"
        },
        "descriptors": {
          "medium": {
            "weight": {
              "value": "{number.font.weight.medium.value}"
            }
          },
          "medium-italic": {
            "weight": {
              "value": "{number.font.weight.medium.value}"
            },
            "style": {
              "value": "italic"
            }
          },
          "semibold": {
            "weight": {
              "value": "{number.font.weight.semibold.value}"
            }
          },
          "semibold-italic": {
            "weight": {
              "value": "{number.font.weight.semibold.value}"
            },
            "style": {
              "value": "italic"
            }
          },
          "bold": {
            "weight": {
              "value": "{number.font.weight.bold.value}"
            }
          },
          "bold-italic": {
            "weight": {
              "value": "{number.font.weight.bold.value}"
            },
            "style": {
              "value": "italic"
            }
          }
        }
      }
    }
  }
}
```

And I have this template (heavily inspired by yours):

```javascript
<%
Object.entries(properties && properties.asset && properties.asset.font || {}).map(([fontSlug, fontProps]) => {

  let formats = fontProps.formats ? fontProps.formats.value : ['woff2', 'woff'];
  let display = fontProps.display ? fontProps.display.value : 'swap';

  Object.entries(fontProps.descriptors || {}).map(([descriptorKey, descriptorProps]) => {

    let style = descriptorProps.style ? descriptorProps.style.value : 'normal';
    let weight = descriptorProps.weight.value;
    let files = [];

    formats.forEach(format => {
      let url = `dist/assets/fonts/${fontSlug}/${fontSlug}-${descriptorKey}.${format}`;
      files.push(`url("${url}") format(${format})`);
    });
%>
@font-face {
  font-family: "<%= fontProps.family.value %>";
  src: <%= files.join(',\n\t\t   ') %>;
  font-style: <%= style %>;
  font-weight: <%= weight %>;
  font-display: <%= display %>;
}
<%
  });
}); %>
```

And here's the resulting CSS:

```css

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-medium.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-medium.woff") format(woff);
  font-style: normal;
  font-weight: 500;
  font-display: swap;
}

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-medium-italic.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-medium-italic.woff") format(woff);
  font-style: italic;
  font-weight: 500;
  font-display: swap;
}

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-semibold.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-semibold.woff") format(woff);
  font-style: normal;
  font-weight: 600;
  font-display: swap;
}

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-semibold-italic.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-semibold-italic.woff") format(woff);
  font-style: italic;
  font-weight: 600;
  font-display: swap;
}

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-bold.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-bold.woff") format(woff);
  font-style: normal;
  font-weight: 700;
  font-display: swap;
}

@font-face {
  font-family: "Sharp Sans";
  src: url("dist/assets/fonts/sharpsans/sharpsans-bold-italic.woff2") format(woff2),
		   url("dist/assets/fonts/sharpsans/sharpsans-bold-italic.woff") format(woff);
  font-style: italic;
  font-weight: 700;
  font-display: swap;
}
```
