### ISSUE TITLE
custom format for CSS variables with generated Sass @if statement

### ISSUE THREAD

**Issue by sturobson** [amzn/style-dictionary#786]
I have created a format that would wrap the outputted CSS custom properties inside an `@if` statement in the `.scss` file.

```javascript
StyleDictionaryPackage.registerFormat({
  name: 'css/variables',
  formatter: function (dictionary) {
    return `
    @if global-variable-exists(use_custom_properties) {
     ${dictionary.allProperties.map(prop => `--${prop.name}: ${prop.value};`).join('\n	')}
    }`	
  }
});
```

What I would _love_ to be able to do is have that `@if` statement also check if there is a Sass variable that is specific to the generated file in existance.

So taking this `.json`:

```json 
{
  "border": {
    "color": {
      "primary": {
        "value": "{color.neutral.900}"
      }
    }
  }
}
```

Currently the custom format would create:

```scss
@if global-variable-exists(use_custom_properties) {
  --border-color-primary: #000000;
}
```

I'd like the initial `border` or whatever it is to be used to create the extra `@if` statement. So the outputted file would be:

```scss
@if global-variable-exists(use_custom_properties) or
@if global-variable-exists(use_custom_properties__border) {
  --border-color-primary: #000000;
}
```

Any ideas how I'd get the `border` from the `.json` file?
