### ISSUE TITLE
Is it possible to generate CSS classes from tokens?

### ISSUE THREAD

**Issue by nareshbhatia** [amzn/style-dictionary#798]
So far I have been very successful in generating CSS variables from design tokens. But is it possible to generate CSS classes from tokens?

### Example
I have a token like this one:

```json
{
  "h1": {
    "value": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": 1.2,
      "fontSize": "1rem",
    },
    "type": "typography"
  }
}
```

After conversion it should look like this:

```css
.h1 {
  font-family: Inter;
  font-weight: 400;
  line-height: 1.2;
  font-size: 1rem;
}
```

Currently I am getting

```
--h1: [object Object];
```
