### ISSUE TITLE
Feature request: Log level control for pre-defined formats

### ISSUE THREAD

**Issue by otaviomad** [amzn/style-dictionary#814]
Hey,

I've been using SD to implement design tokens in our company. In our current way of working, we're spreading stuff in multiple files which reference variables only present in other files, while using `outputReferences`.

One use case for this is having a component consume a variable color, as defined by a theme with a css selector. For example:
```css
/* themes/blue.css */
.theme-blue {
  --default-color: blue
}

/* components/button.css */
.button {
  background-color: var(--default-color)
}
```

however, when using this approach, we invariably get hit with a barrage of warning messages saying `While building components/button.css, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file`.

This ends up hiding actual important messages that may crop up during the build process and the warning itself is irrelevant, since this is the intende output.

Perhaps a good idea would be to add an optional "logLevel" property to the format options so that these messages can be filtered out? Thanks!
