### ISSUE TITLE
[ Question ] Is it possible to set the value of a token to a css-variable representation of another token?

### ISSUE THREAD

**Issue by michaelwarren1106** [amzn/style-dictionary#868]
I want to end up with some css like this:

```css
:root {
  --my-color-text-neutral: var(--my-color-slate-900)
}
```

Is there a way I can write my token definitions to achieve this or would this output pretty much be completely custom?
