### ISSUE TITLE
Generate Sass variables referencing CSS custom properties

### ISSUE THREAD

**Issue by SalimBensiali** [amzn/style-dictionary#946]
HI,

Is it possible off the shelf or with custom transforms to generate Sass variables whose values are CSS custom properties? ie, I would like
```yml
button:
  color:
    background:
      primary:
        value: '{color.blue-50.value}'
```

to generate
```scss
$button-color-background-primary: var(--button-color-background-primary)
```

and of course assuming the CSS custom properties are already handled to output
```css
:root {
  --color-blue-50: blue;
  --button-color-background-primary: var(--color-blue-50);
}
```
