### ISSUE TITLE
Conflicts with outputReferences when custom transform changes token value

### ISSUE THREAD

**Issue by germain-gg** [amzn/style-dictionary#974]
I am using [tokens.studio](https://tokens.studio/) and their set of style-dictionary transforms https://github.com/tokens-studio/sd-transforms

Specifically a transform called `ts/resolveMath`. It appears that the transform is applied before the formatting phase. And one part of the system gets confused and the output is invalid CSS. See a more in-depth [investigation by the package maintainer](https://github.com/tokens-studio/sd-transforms/issues/13#issuecomment-1486981956)

## Reproduction steps

```jsonc
{
  "space": {
    "scale": {
      "value": "4",
      "type": "spacing",
      "description": "Base unit for spacing scale."
    },
    "6x": {
      "value": "{space.scale} * 6",
      "type": "spacing"
    },
    "7x": {
      "value": "{space.scale} * 7",
      "type": "spacing"
    }
  }
}
```

And a style-dictionary config of

```js
{
  "transformGroup": "css-tokens",
  "transforms": [
    "ts/resolveMath",
    "ts/size/px",
    "name/cti/kebab"
  ],
  "files": {
    "destination": "style.css",
    "format": "css/variables",
    "options": {
      "outputReferences": true
    }
  }
}
```

### Expected output

```css
:root {
  --space-scale: 4px;
  --space-7x: 28px;
  --space-6x: 24px;
}
```

### Actual output

```css
:root {
  --space-scale: 4px;
  --space-7x: 28px;
  --space-6x: 2var(--space-scale);
}
```
